$PHY_ICDIR/pdec/src/pdec_top.v
$PHY_ICDIR/pdec/src/pdec_para_mng.v
$PHY_ICDIR/pdec/src/pdec_top_ctrl.v
$PHY_ICDIR/pdec/src/pdec_rd_ctrl.v
$PHY_ICDIR/pdec/src/pdec_updt_llr.v
$PHY_ICDIR/pdec/src/pdec_llr_unit.v
$PHY_ICDIR/pdec/src/pdec_updt_pm.v
$PHY_ICDIR/pdec/src/pdec_pm_unit.v
$PHY_ICDIR/pdec/src/pdec_pm_sort.v
$PHY_ICDIR/pdec/src/pdec_botnic_sort.v
$PHY_ICDIR/pdec/src/pdec_sort_unit.v
$PHY_ICDIR/pdec/src/pdec_updt_path.v
$PHY_ICDIR/pdec/src/pdec_lazy_copy.v
$PHY_ICDIR/pdec/src/pdec_updt_us.v
$PHY_ICDIR/pdec/src/pdec_us_unit.v
$PHY_ICDIR/pdec/src/pdec_crc_ck.v
$PHY_ICDIR/pdec/src/pdec_crc_24c.v
$PHY_ICDIR/pdec/src/pdec_sram_top1.v
$PHY_ICDIR/pdec/src/pdec_dp2sp.v
$PHY_ICDIR/pdec/src/pdec_rom_stage.v
$PHY_ICDIR/pdec/src/pdec_rom_depth.v
$PHY_ICDIR/pdec/reg/pdec_reg_dyn_cch.v
